cargo-features = ["profile-rustflags"]

[package]
name = "q10"
version = "0.1.0"
edition = "2024"

[dependencies]
hashbrown = "0.16.1"
itertools = "0.14.0"

[profile.release]
codegen-units = 1
lto = "fat"
rustflags = ["-C", "target-cpu=native"]
opt-level = 3
debug = 2
