cargo-features = ["profile-rustflags"]

[package]
name = "q7"
version = "0.1.0"
edition = "2024"

[dependencies]

[profile.release]
codegen-units = 1
lto = "fat"
rustflags = ["-C", "target-cpu=native"]
opt-level = 3
# debug = true
